name: Auto Create PR

on:
  push:
    branches-ignore:
      - '*'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Debug
      run: |
        echo "Checking for keyword in commit message..."
        if git log --format=%B -n 1 ${{ github.sha }} | grep -i 'feature-request'; then
          echo "Keyword found! Creating a pull request..."
        else
          echo "No keyword found. Not creating a pull request."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
